Issue#2238: some syntax errors from *args or **kwargs expressions would give bogus error messages, because of untested exceptions::
    >>> f(**g(1=2))
    XXX undetected error
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    TypeError: 'int' object is not iterable

instead of the expected SyntaxError: keyword can't be an expression

Will backport.

--HG--
branch : legacy-trunk