Fix the bug Sjoerd Mullender discovered, where find_from_args() wasn't trying hard enough to find out what the arguments to an import were. There is no test-case for this bug, yet, but this is what it looked like:
from encodings import cp1006, cp1026
ImportError: cannot import name cp1026

'__import__' was called with only the first name in the 'arguments' list.

--HG--
branch : legacy-trunk